site_name: IT Knowledge Base
site_url: https://brady-kcm.github.io/it-kb/

theme:
  name: material
  logo: assets/shi-logo.png
  
  features:
  # links all content types of the same title together. (ex. if you click windows all windows tabs show)
    - content.tabs.link

  palette: 
    scheme: slate
    primary: blue
    accent: deep orange

markdown_extensions:
  - admonition
  # allows sizing of images
  - attr_list
  # adds content tabs
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true