site_name: IT Knowledge Base
site_url: https://brady-kcm.github.io/it-kb/

theme:
  name: material
  logo: /assets/shi-logo.png

  palette: 
    scheme: slate
    primary: blue
    accent: deep orange

markdown_extensions:
  - admonition