site_name: IT Knowledge Base
site_url: https://brady-kcm.github.io/it-kb/

theme:
  name: material
  logo: assets/shi-logo.png
  
  features:
  # links all content types of the same title together. (ex. if you click windows all windows tabs show)
    - content.tabs.link
    - navigation.footer

  palette: 
    scheme: slate
    primary: blue
    accent: deep orange

nav:
  - Welcome: index.md
  - Office Migration:
    - Migration vs Archival: Office Migration/Migration vs Archival.md
    - Google Takeout: Office Migration/Google Takeout.md
    - Gmail: Office Migration/Gmail.md
    - Google Drive: Office Migration/Google Drive.md
    - Google Calendar: Office Migration/Google Calendar.md
    - Google Contacts: Office Migration/Google Contacts.md

markdown_extensions:
  - admonition
  # allows sizing of images
  - attr_list
  # adds content tabs
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

extra:
  generator: false